### ISSUE TITLE
Cannot run console application in Visual Studio under debugger

### ISSUE THREAD

**Issue by bladeoflight16** [chucknorris/roundhouse#115]
I'm trying to work on fixing an issue in RoundhousE, and I can't run the console app under Visual Studio's debugger. (I was originally trying to work with only the tests, but that's having it's own set of weird issues.) I've set the project to use these command line parameters when I attempt to run the console: `--dt="pg" --server=localhost --database=test`. As you can see, I'm setting the database type to PostgreSQL. This results in this error:

```
StructureMap.StructureMapException was caught
  Message=StructureMap Exception Code:  207
Internal exception while creating Instance 'bc250f25-6230-4781-8951-060205a1c9f0' of PluginType roundhouse.databases.Database, roundhouse, Version=0.8.6.0, Culture=neutral, PublicKeyToken=91b86fd44f1f23bc.  Check the inner exception for more details.
  Source=StructureMap
  ErrorCode=207
  StackTrace:
       at StructureMap.Pipeline.LambdaInstance`1.build(Type pluginType, BuildSession session) in c:\code\structuremap\Source\StructureMap\Pipeline\LambdaInstance.cs:line 29
       at StructureMap.Pipeline.Instance.createRawObject(Type pluginType, BuildSession session) in c:\code\structuremap\Source\StructureMap\Pipeline\Instance.cs:line 103
       at StructureMap.Pipeline.Instance.Build(Type pluginType, BuildSession session) in c:\code\structuremap\Source\StructureMap\Pipeline\Instance.cs:line 69
       at StructureMap.Pipeline.ObjectBuilder.ConstructNew(Type pluginType, Instance instance, BuildSession session) in c:\code\structuremap\Source\StructureMap\Pipeline\ObjectBuilder.cs:line 39
       at StructureMap.Pipeline.ObjectBuilder.Resolve(Type pluginType, Instance instance, BuildSession session) in c:\code\structuremap\Source\StructureMap\Pipeline\ObjectBuilder.cs:line 27
       at StructureMap.BuildSession.CreateInstance(Type pluginType, Instance instance) in c:\code\structuremap\Source\StructureMap\BuildSession.cs:line 153
       at StructureMap.BuildSession.<>c__DisplayClass3.<.ctor>b__1() in c:\code\structuremap\Source\StructureMap\BuildSession.cs:line 34
       at StructureMap.BuildSession.CreateInstance(Type pluginType) in c:\code\structuremap\Source\StructureMap\BuildSession.cs:line 192
       at StructureMap.Container.GetInstance(Type pluginType) in c:\code\structuremap\Source\StructureMap\Container.cs:line 265
       at StructureMap.Container.GetInstance[T]() in c:\code\structuremap\Source\StructureMap\Container.cs:line 155
       at StructureMap.ObjectFactory.GetInstance[PLUGINTYPE]() in c:\code\structuremap\Source\StructureMap\ObjectFactory.cs:line 131
       at roundhouse.infrastructure.app.ApplicationConfiguraton.build_items_for_container(ConfigurationPropertyHolder configuration_property_holder) in c:\dev\roundhouse\repo\product\roundhouse\infrastructure.app\ApplicationConfiguraton.cs:line 191
       at roundhouse.infrastructure.app.ApplicationConfiguraton.build_the_container(ConfigurationPropertyHolder configuration_property_holder) in c:\dev\roundhouse\repo\product\roundhouse\infrastructure.app\ApplicationConfiguraton.cs:line 161
       at roundhouse.console.Program.set_up_configuration_and_build_the_container(String[] args) in c:\dev\roundhouse\repo\product\roundhouse.console\Program.cs:line 76
       at roundhouse.console.Program.Main(String[] args) in c:\dev\roundhouse\repo\product\roundhouse.console\Program.cs:line 46
  InnerException: System.NullReferenceException
       Message=A type could not be created from the object you passed. "roundhouse.databases.postgresql.PostgreSQLDatabase, roundhouse.databases.postgresql" resolves to null.
       Source=roundhouse
       StackTrace:
            at roundhouse.infrastructure.loaders.DefaultInstanceCreator.create_object_from_string_type(String object_to_create) in c:\dev\roundhouse\repo\product\roundhouse\infrastructure\loaders\DefaultInstanceCreator.cs:line 27
            at roundhouse.infrastructure.loaders.DefaultInstanceCreator.create_object_from_string_type[T](String object_to_create) in c:\dev\roundhouse\repo\product\roundhouse\infrastructure\loaders\DefaultInstanceCreator.cs:line 19
            at roundhouse.infrastructure.app.builders.DatabaseBuilder.build(FileSystemAccess file_system, ConfigurationPropertyHolder configuration_property_holder) in c:\dev\roundhouse\repo\product\roundhouse\infrastructure.app\builders\DatabaseBuilder.cs:line 32
            at roundhouse.infrastructure.app.ApplicationConfiguraton.<>c__DisplayClass5.<build_items_for_container>b__1(IContext context) in c:\dev\roundhouse\repo\product\roundhouse\infrastructure.app\ApplicationConfiguraton.cs:line 178
            at StructureMap.Pipeline.LambdaInstance`1.build(Type pluginType, BuildSession session) in c:\code\structuremap\Source\StructureMap\Pipeline\LambdaInstance.cs:line 25
       InnerException: 
```

Adding a reference to the `roundhouse.databases.postgresql` to the console application seems to fix this error. I can submit a pull request for this change if you want, but I wanted to ask about it first. I'm not sure if that would break anything else, and I also wanted to know if any other of the database projects should be added as a reference.

**Comment by erikbra** [comment]
Trying to clean up a bit of old issues. Any objections if I close this, @bladeoflight16 ?

**Comment by bladeoflight16** [comment]
@erikbra  It has been ages since I've tried this, so I can't either confirm or deny that it's still an issue. Feel free to close.

**Comment by erikbra** [comment]
I fully understand :) the issue was opened 7 years ago. I'll close the issue, and if someone else is having a similar issue, I guess they will open a new one.
