### ISSUE TITLE
New Chocolatey Release

### ISSUE THREAD

**Issue by mlb5000** [chucknorris/roundhouse#167]
Could someone please cut a new Chocolatey release for this? 0.8.6 is from November 2013, and someone integrated an updated Npgsql version a couple months back that fixes getting this error every time the program completes even though the entire migration process succeeded:

    Cannot access a disposed object.
    Object name: 'NpgsqlConnection'.
    System.ObjectDisposedException: Cannot access a disposed object.
    Object name: 'NpgsqlConnection'.
       at Npgsql.NpgsqlConnection.CheckNotDisposed()
       at Npgsql.NpgsqlConnection.get_FullState()
       at Npgsql.NpgsqlConnection.get_State()
       at roundhouse.databases.DefaultDatabase`1.dispose_connection(IConnection`1 connection)
       at roundhouse.databases.DefaultDatabase`1.Dispose()
       at roundhouse.runners.RoundhouseMigrationRunner.run()
       at roundhouse.console.Program.run_migrator(ConfigurationPropertyHolder configuration)
       at roundhouse.console.Program.Main(String[] args)

**Comment by ferventcoder** [comment]
@ChrisMissal has put a stake in the ground on 0.8.7 - watch https://github.com/chucknorris/roundhouse/milestones and https://github.com/chucknorris/roundhouse/milestones/Release%200.8.7 specifically.
