### ISSUE TITLE
Alter database scripts running in transaction when shouldn't be

### ISSUE THREAD

**Issue by hulahomer** [chucknorris/roundhouse#183]
I am running on the latest version of RoundhousE, version 0.8.6.297 and when I included a script in the alterDatabase with the following content:

`ALTER DATABASE [Test] MODIFY FILE ( NAME = N'Test', SIZE= 10GB, FILEGROWTH = 20GB )`

It threw an InvalidOperationException, which appears to be due to it running the query inside of a transaction, and alter database scripts for SQL Server are not allowed to be a part of an implicit or explicit transaction, and from previous issues I have seen here, they should not be running inside a transaction, like mentioned [here](https://github.com/chucknorris/roundhouse/pull/79#issuecomment-8356054)

I plan to try and submit a pull request to address this, but after talking with @ChrisMissal I wanted to first open this ticket to ensure no one else has already seen this recently.

Below is the relevant parts of the debug log showing the error I am getting:

```2015-03-30 15:32:28,840 [INFO ] - Migration Scripts
2015-03-30 15:32:28,840 [DEBUG] - Opening admin connection to 'data source=(local);initial catalog=master;Integrated Security=SSPI;'
2015-03-30 15:32:28,856 [INFO ] - Looking for AlterDatabase scripts in ".\Database\Test\alterDatabase".
2015-03-30 15:32:28,856 [DEBUG] -  Found and running .\Database\Test\alterDatabase\0001-filegrowth_settings.sql.
2015-03-30 15:32:28,871 [DEBUG] - Repository found 0 records of type ScriptsRun.
2015-03-30 15:32:28,871 [DEBUG] - Repository found 0 records of type ScriptsRun with criteria NHibernate.Criterion.QueryOver`2[roundhouse.model.ScriptsRun,roundhouse.model.ScriptsRun].
2015-03-30 15:32:28,887 [DEBUG] - Repository found 0 records of type ScriptsRun with criteria NHibernate.Criterion.QueryOver`2[roundhouse.model.ScriptsRun,roundhouse.model.ScriptsRun].
2015-03-30 15:32:28,887 [DEBUG] - Checking to see if 0001-filegrowth_settings.sql is an environment file. We are in the Integration environment.
2015-03-30 15:32:28,887 [DEBUG] - Repository found 0 records of type ScriptsRun with criteria NHibernate.Criterion.QueryOver`2[roundhouse.model.ScriptsRun,roundhouse.model.ScriptsRun].
2015-03-30 15:32:28,887 [INFO ] -  Running 0001-filegrowth_settings.sql on (local) - Test.
2015-03-30 15:32:28,902 [DEBUG] - [SQL] Running (on connection 'Admin'): 
ALTER DATABASE [Test] MODIFY FILE ( NAME = N'Test', SIZE= 10GB, FILEGROWTH = 20GB )
2015-03-30 15:32:28,902 [DEBUG] - Setting up command for admin connection
2015-03-30 15:32:28,902 [ERROR] - Error executing file '0001-filegrowth_settings.sql': statement running was 'ALTER DATABASE [Test] MODIFY FILE ( NAME = N'Test', SIZE= 10GB, FILEGROWTH = 20GB )'
2015-03-30 15:32:28,902 [DEBUG] - Rolling back changes
2015-03-30 15:32:28,902 [DEBUG] - Recording 0001-filegrowth_settings.sql script ran with error on (local) - Test.
2015-03-30 15:32:28,902 [DEBUG] - Saved item of type ScriptsRunError successfully.
2015-03-30 15:32:28,902 [DEBUG] - Closing connection
2015-03-30 15:32:28,918 [ERROR] - RoundhousE encountered an error. You were running in a transaction though, so the database should be in the state it was in prior to this piece running. This does not include a drop/create or any creation of a database, as those items can not run in a transaction.
System.InvalidOperationException: The transaction is either not associated with the current connection or has been completed.
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(DbAsyncResult result, String methodName, Boolean sendToPipe)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at roundhouse.databases.AdoNetDatabase.run_command_with(String sql_to_run, ConnectionType connection_type, IList`1 parameters)
   at roundhouse.databases.AdoNetDatabase.run_sql(String sql_to_run, ConnectionType connection_type, IList`1 parameters)
   at roundhouse.databases.DefaultDatabase`1.run_sql(String sql_to_run, ConnectionType connection_type)
   at roundhouse.migrators.DefaultDatabaseMigrator.run_sql(String sql_to_run, String script_name, Boolean run_this_script_once, Boolean run_this_script_every_time, Int64 version_id, Environment environment, String repository_version, String repository_path, ConnectionType connection_type)
   at roundhouse.runners.RoundhouseMigrationRunner.traverse_files_and_run_sql(String directory, Int64 version_id, MigrationsFolder migration_folder, Environment migrating_environment, String repository_version, ConnectionType connection_type)
   at roundhouse.runners.RoundhouseMigrationRunner.log_and_traverse(MigrationsFolder folder, Int64 version_id, String new_version, ConnectionType connection_type)
   at roundhouse.runners.RoundhouseMigrationRunner.run()```

**Comment by wokket** [comment]
Yep, definately biting me as well.  We run all our migrations with /transaction to ensure clean rollback on script failure, but it seemingly makes it impossible to use the AlterDatabase scripts, as they fail to enlist as seen in your trace above.

**Comment by KorsG** [comment]
+1

**Comment by stimms** [comment]
+1

**Comment by wokket** [comment]
Hi,

This has bitten us *again* on our latest project, and I've forked the code to try and resolve the issue.  The actual code change to prevent enlisting in a transaction that won't work is pretty simple, and can be previewed here: https://github.com/wokket/roundhouse/commit/7a9b0af7909722932db9ca89fc8cee26f63e1954

However the actual database upgrade still fails due to the NHibernate Session having an open connection on the target database, preventing the ALTER DATABASE from completing, per the below output from sp_whoisactive

![image](https://cloud.githubusercontent.com/assets/3802829/20542116/f60f1cd0-b14b-11e6-9e81-569d4aa4ee68.png)


I'm rapidly getting out of my depth here, can someone that knows the tool point me in the best direction for how to prevent this Session connection from hanging around idling through the ALTER DATABASE portion of the migration?

Thanks

**Comment by mikesigs** [comment]
Just ran into this today while trying to create a full text catalog. Any chance this will be fixed?

**Comment by mikesigs** [comment]
I found that in the latest version (as of writing it's 0.9.1) there are two new command line switches available where you can specify scripts to run before and after migrations, and outside of a transaction. They don't seem to be enabled by default though. In my case I needed to create some full-text indexes (not ALTER DATABASE). So I created a folder 'afterMigration' and specified on the command line `--aftermigrationfolder="afterMigration"`, and then added my scripts. I think since these scripts will be run every time, you have to be careful to wrap your modifications in `IF NOT EXISTS` checks. Sorry, I know it's not specific fix for this issue, but figured I'd share my related issue and how I solved it.
