### ISSUE TITLE
Long file path handling in 'copy_to_change_drop_folder'

### ISSUE THREAD

**Issue by StevenLiekens** [chucknorris/roundhouse#214]
As a convention, I use the scripted object's fully qualified name as the file name of each script. These names can get very lengthy. This works, but the code in `RoundhouseMigrationRunner.copy_to_change_drop_folder(string, Folder)` is hitting the `MAX_PATH` limit.

    System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
       at System.IO.Path.SafeSetStackPointerValue(Char* buffer, Int32 index, Char value)
       at System.IO.Path.NormalizePathFast(String path, Boolean fullCheck)
       at System.IO.Path.NormalizePath(String path, Boolean fullCheck)
       at System.IO.Path.GetFullPathInternal(String path)
       at System.IO.Path.GetFullPath(String path)
       at roundhouse.infrastructure.filesystem.WindowsFileSystemAccess.get_directory_name_from(String file_path)
       at roundhouse.runners.RoundhouseMigrationRunner.copy_to_change_drop_folder(String sql_file_ran, Folder migration_folder)
       at roundhouse.runners.RoundhouseMigrationRunner.traverse_files_and_run_sql(String directory, Int64 version_id, MigrationsFolder migration_folder, Environment migrating_environment, String repository_version, ConnectionType connection_type)

**Comment by ferventcoder** [comment]
Perhaps we just ticket this as LFN (Long File Name) Handling in general.
