### ISSUE TITLE
OutOfMemoryException in roundhouse.sqlsplitters.StatementSplitter.split_sql_on_regex_and_remove_empty_statements

### ISSUE THREAD

**Issue by StevenLiekens** [chucknorris/roundhouse#216]
Not really a bug or anything, but I noticed that RH doesn't handle large files well. I tried to insert 300MB of data and it crashed the program.

````
RoundhousE encountered an error.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at roundhouse.sqlsplitters.StatementSplitter.split_sql_on_regex_and_remove_empty_statements(String sql_to_run, String sql_statement_separator_regex_pattern)
   at roundhouse.migrators.DefaultDatabaseMigrator.get_statements_to_run(String sql_to_run)
   at roundhouse.migrators.DefaultDatabaseMigrator.run_sql(String sql_to_run, String script_name, Boolean run_this_script_once, Boolean run_this_script_every_time, Int64 version_id, Environment environment, String repository_version, String repository_path, ConnectionType connection_type)
   at roundhouse.runners.RoundhouseMigrationRunner.traverse_files_and_run_sql(String directory, Int64 version_id, MigrationsFolder migration_folder, Environment migrating_environment, String repository_version, ConnectionType connection_type)
   at roundhouse.runners.RoundhouseMigrationRunner.log_and_traverse(MigrationsFolder folder, Int64 version_id, String new_version, ConnectionType connection_type)
   at roundhouse.runners.RoundhouseMigrationRunner.run()
Exception of type 'System.OutOfMemoryException' was thrown.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at roundhouse.sqlsplitters.StatementSplitter.split_sql_on_regex_and_remove_empty_statements(String sql_to_run, String sql_statement_separator_regex_pattern)
   at roundhouse.migrators.DefaultDatabaseMigrator.get_statements_to_run(String sql_to_run)
   at roundhouse.migrators.DefaultDatabaseMigrator.run_sql(String sql_to_run, String script_name, Boolean run_this_script_once, Boolean run_this_script_every_time, Int64 version_id, Environment environment, String repository_version, String repository_path, ConnectionType connection_type)
   at roundhouse.runners.RoundhouseMigrationRunner.traverse_files_and_run_sql(String directory, Int64 version_id, MigrationsFolder migration_folder, Environment migrating_environment, String repository_version, ConnectionType connection_type)
   at roundhouse.runners.RoundhouseMigrationRunner.log_and_traverse(MigrationsFolder folder, Int64 version_id, String new_version, ConnectionType connection_type)
   at roundhouse.runners.RoundhouseMigrationRunner.run()
   at roundhouse.console.Program.run_migrator(ConfigurationPropertyHolder configuration)
   at roundhouse.console.Program.Main(String[] args)
````

**Comment by afrew** [comment]
Is there a recommended workaround for this issue? I can't get roundhouse to run large data scripts and have to resort to other tools

**Comment by erikbra** [comment]
I would really like to fix this, but do you think you can provide some sample data that demonstrates the error? Is it just any large SQL file? Then it could probably be demonstrated in a unit test.
