### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'roundhouse.databases.sqlserver'

### ISSUE THREAD

**Issue by dquser** [chucknorris/roundhouse#230]
We are getting the following exception occasionally:

System.IO.FileNotFoundException: Could not load file or assembly 'roundhouse.databases.sqlserver' or one of its dependencies. The system cannot find the file specified.
File name: 'roundhouse.databases.sqlserver'

We currently updated our automated deployment scripts to run RoundhousE in parallel. Thus we ended up with 10 instances or so of RoundhousE running in parallel. This works just fine in a couple of servers, but it fails occasionally with the exception above in other server we have.

Issue 160 (https://github.com/chucknorris/roundhouse/issues/160) also addresses this exception, which the user attributed to his database being run under single user mode. Unfortunately, that's not our case. I'm wondering if you have observed this exception before? Thank you so much!

Running RoundhousE v0.8.6.268 against [SERVER] - [DATABASE].
Looking in [PATH] for scripts to run.
Setup, Backup, Create/Restore/Drop
Creating [DATABASE] database on [SERVER] server if it doesn't exist.
RoundhousE encountered an error.
System.IO.FileNotFoundException: Could not load file or assembly 'roundhouse.databases.sqlserver' or one of its dependencies. The system cannot find the file specified.
File name: 'roundhouse.databases.sqlserver'
at System.Reflection.Assembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)
at System.Reflection.Assembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)
at System.Reflection.Assembly.InternalLoad(AssemblyName assemblyRef, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
at System.Reflection.Assembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
at System.Reflection.Assembly.Load(String assemblyString)
at roundhouse.infrastructure.loaders.DefaultAssemblyLoader.load_assembly(String assembly_name)
at roundhouse.infrastructure.persistence.NHibernateSessionFactoryBuilder.build_session_factory(Action`1 additional_function)
at roundhouse.databases.DefaultDatabase`1.set_repository()
at roundhouse.databases.AdoNetDatabase.open_connection(Boolean with_transaction)
at roundhouse.migrators.DefaultDatabaseMigrator.open_connection(Boolean with_transaction)
at roundhouse.runners.RoundhouseMigrationRunner.run()
WRN: Assembly binding logging is turned OFF.

**Comment by ferventcoder** [comment]
Running in parallel pointing to completely different databases right?

**Comment by dquser** [comment]
Yes! We were running on parallel to two different databases (same server though).

**Comment by ferventcoder** [comment]
@dquser interesting. Not really a recommended scenario but interesting. It's likely what is happening is a file lock.

**Comment by ferventcoder** [comment]
Are you running a released version of RoundhousE or a self-built one?

**Comment by dquser** [comment]
We were running a released version of RoundhousE (0.8.6.268).

**Comment by dquser** [comment]
Thank You!

**Comment by greg-murray-volusion** [comment]
I'm running into the same issue trying to run a forked version of 0.8.6.  Was there any resolution to this one?

**Comment by mortb** [comment]
@greg-murray-volusion: for us it was due to the database being set as SINGLE_USER = issue #160 
Old issue, but I thought I'd leave a comment if anyone else encounters the issue.
