### ISSUE TITLE
Roundhouse fails when FIPS mode is enabled

### ISSUE THREAD

**Issue by bladeoflight16** [chucknorris/roundhouse#249]
Unfortunately, there is a nasty little feature of Windows Server 2012 (and possibly other versions, but I have not checked) called [FIPS Mode](http://blogs.technet.com/b/secguide/archive/2014/04/07/why-we-re-not-recommending-fips-mode-anymore.aspx). This disabled whatever hash algorithm RoundhousE is using, resulting in the following error from the latest version on NuGet:

```
StructureMap Exception Code:  207
Internal exception while creating Instance '54ceaf40-a5eb-4e95-86b0-a3f804eb57a4' of PluginType roundhouse.migrators.DatabaseMigrator, rh, Version=0.8.6.0, Culture=neutral, PublicKeyToken=null.  Check the inner exception for more details.
StructureMap.StructureMapException: StructureMap Exception Code:  207
Internal exception while creating Instance '54ceaf40-a5eb-4e95-86b0-a3f804eb57a4' of PluginType roundhouse.migrators.DatabaseMigrator, rh, Version=0.8.6.0, Culture=neutral, PublicKeyToken=null.  Check the inner exception for more details. ---> StructureMap.StructureMapException: StructureMap Exception Code:  207
Internal exception while creating Instance '0edb8085-8ed5-4418-b46e-971c2b3f0717' of PluginType roundhouse.cryptography.CryptographicService.  Check the inner exception for more details. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeConstructor(Object[] args, SignatureStruct& signature, IntPtr declaringType)
   at System.RuntimeMethodHandle.InvokeConstructor(Object[] args, SignatureStruct signature, RuntimeTypeHandle declaring
Type)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, Cultu
reInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create(String algName)
   at System.Security.Cryptography.MD5.Create()
   at roundhouse.cryptography.MD5CryptographicService..ctor()
   at lambda_method(ExecutionScope , IArguments )
   at StructureMap.Construction.BuilderCompiler.FuncCompiler`1.<>c__DisplayClass2.<CreateBuilder>b__0(IArguments args)
   at StructureMap.Construction.InstanceBuilder.BuildInstance(IArguments args)
   at StructureMap.Pipeline.ConstructorInstance.Build(Type pluginType, BuildSession session, IInstanceBuilder builder)
   --- End of inner exception stack trace ---
   at StructureMap.Pipeline.ConstructorInstance.Build(Type pluginType, BuildSession session, IInstanceBuilder builder)
   at StructureMap.Pipeline.ConstructorInstance.build(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.SmartInstance`1.build(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.Instance.createRawObject(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.Instance.Build(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.ObjectBuilder.ConstructNew(Type pluginType, Instance instance, BuildSession session)
   at StructureMap.Pipeline.ObjectBuilder.Resolve(Type pluginType, Instance instance, BuildSession session)
   at StructureMap.BuildSession.CreateInstance(Type pluginType, Instance instance)
   at StructureMap.BuildSession.<>c__DisplayClass3.<.ctor>b__1()
   at StructureMap.BuildSession.CreateInstance(Type pluginType)
   at StructureMap.BuildSession.GetInstance[T]()
   at roundhouse.infrastructure.app.ApplicationConfiguraton.<>c__DisplayClass5.<build_items_for_container>b__3(IContext
context)
   at StructureMap.Pipeline.LambdaInstance`1.build(Type pluginType, BuildSession session)
   --- End of inner exception stack trace ---
   at StructureMap.Pipeline.LambdaInstance`1.build(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.Instance.createRawObject(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.Instance.Build(Type pluginType, BuildSession session)
   at StructureMap.Pipeline.ObjectBuilder.ConstructNew(Type pluginType, Instance instance, BuildSession session)
   at StructureMap.Pipeline.ObjectBuilder.Resolve(Type pluginType, Instance instance, BuildSession session)
   at StructureMap.BuildSession.CreateInstance(Type pluginType, Instance instance)
   at StructureMap.BuildSession.<>c__DisplayClass3.<.ctor>b__1()
   at StructureMap.BuildSession.CreateInstance(Type pluginType)
   at StructureMap.Container.GetInstance(Type pluginType)
   at StructureMap.Container.GetInstance[T]()
   at roundhouse.infrastructure.containers.custom.StructureMapContainer.Resolve[TypeToReturn]()
   at roundhouse.infrastructure.containers.Container.get_an_instance_of[TypeToGet]()
   at roundhouse.console.Program.get_migration_runner(ConfigurationPropertyHolder configuration)
   at roundhouse.console.Program.run_migrator(ConfigurationPropertyHolder configuration)
   at roundhouse.console.Program.Main(String[] args)
```

A solution would be to switch to SHA-1, as the .NET SHA-1 algorithm _is_ FIPS approved, but this poses some serious challenges when migrating from Windows Server 2008 R2 to Windows Server 2012. The only solution I can think of would be to re-hash all the scripts already run with an "approved" algorithm, unless there's a FIPS approved MD5 algorithm in .NET.

**Comment by ErikEJ** [comment]
Microsoft recommends that you disable the FIPS feature...

**Comment by bladeoflight16** [comment]
No, they don't recommend turning it on. Read the last paragraph in the link:

> Government regulations may continue to mandate that FIPS mode be enabled on government computers running Windows. Our updated recommendations do not contradict or conflict with government guidance: we’re not telling customers to turn it off – our recommendation is that it’s each customer’s decision to make. Our updated guidance reflects our belief there is not a compelling reason for our customers that are not subject to government regulations to enable FIPS mode.

**Comment by ferventcoder** [comment]
Yep, it's the hashing algorithm. Choco is overcoming that now. I think there may have also already been an issue listed here for RH to allow for SHA1/SHA2 hashing.

The catch is that you can't just switch to it and be good. It needs the baselining working first.

**Comment by bladeoflight16** [comment]
There's no possibility of just updating the hashes as some kind of one time operation? The entire file content is stored in the table, after all. There would be no dependency on some kind of baselining then.

**Comment by ferventcoder** [comment]
That one time operation ***is*** the baselining feature.

**Comment by ronnieoverby** [comment]
Could you cheat FIPS mode by including your own MD5 implementation in RoundHouse?

Linqpad script:
 
https://gist.github.com/ronnieoverby/ae2cdbe416c4e854f1e2b6bee9fcc324

Here's were I found the implementation: https://www.jeff.wilcox.name/2008/03/silverlight-2-md5/

**Comment by ferventcoder** [comment]
@ronnieoverby interesting - not sure about rolling our own hashing algorithm. It feels a bit risky.

**Comment by ronnieoverby** [comment]
You're not rolling your own... someone else did it :)

I hear what you're saying, though... The thing is... you're not using it in a security-critical fashion, as far as I can tell. RoundHouse just uses it for determining which scripts have been ran, correct?

**Comment by ferventcoder** [comment]
@ronnieoverby that's exactly right. Which makes it super important to know that it has tests on running it versus the actual algorithm to ensure that there is no difference in output.

**Comment by ferventcoder** [comment]
I wasn't speaking risky from the perspective of security. I was speaking risky from the perspective of breaking existing users.

**Comment by ronnieoverby** [comment]
Agreed. It needs to be tested for parity with the officially supported MD5 algorithm. I would think a unit test that tested against a-millionty-bazillion randomly generated byte sequences would have you feeling pretty safe.

**Comment by ferventcoder** [comment]
+1 for "a-millionty-bazillion" - that made me laugh!

**Comment by bladeoflight16** [comment]
If you're going to go to all the trouble of implementing your own, you may as well just call the native one that *is* FIPS approved. Not sure what that entails. It might just be passing the right arguments to the right classes in the standard crypto lib, but at worst, it would be a DLL import. MS says that implementation is slower than the native .NET one, though.

**Comment by ronnieoverby** [comment]
Fips approved md5? Isnt the algorithm broken?

**Comment by bladeoflight16** [comment]
No, the algorithm works fine. It's just *disabled* by FIPS mode. All "FIPS mode" does is try to disable certain algorithms that haven't had their source code reviewed by some government body:

> An **implementation** of an approved cryptographic algorithm is considered FIPS 140-compliant only if it has been submitted for and has passed National Institute of Standards and Technology (NIST) validation.

(emphasis mine)

We have no reason to believe anything is actually wrong with the disabled implementations. There's a native one that is FIPS approved and so isn't disabled, though.

**Comment by ronnieoverby** [comment]
@bladeoflight16 I checked the annexes listing various approved functions at https://en.wikipedia.org/wiki/FIPS_140-2 and I haven't seen any evidence that there is an approved MD5 implementation. I haven't seen anything to that effect after googling. Where do you get your information?

**Comment by ferventcoder** [comment]
I don't believe MD5 is FIPS approved.
