### ISSUE TITLE
Running build.bat on Windows 10 Parallels NAnt issue

### ISSUE THREAD

**Issue by jsouthron** [chucknorris/roundhouse#262]
I am posting this for users who are running Parallels on OSx and trying to run build.bat on Windows 10.  To be sure, this is not an issue with roundhouse.  If you clone the repo to a shared drive between Parallels and Windows 10, you will get the error below when running build.bat.  To avoid this error, you must copy the project to C:\ and make sure that NAnt is unzipped properly as has been well documented here -> (https://github.com/nant/nant/issues/116).

Hope this helps, cheers.        

```
S:\roundhouse>build
log4net:ERROR XmlConfigurator: Failed to initialize configuration file watcher for file [S:\roundhouse\lib\Nant\NAnt.exe.config]
System.Security.SecurityException: Request failed.
   at log4net.Config.XmlConfigurator.ConfigureAndWatchHandler..ctor(ILoggerRepository repository, FileInfo configFile)
   at log4net.Config.XmlConfigurator.ConfigureAndWatch(ILoggerRepository repository, FileInfo configFile)
The action that failed was:
LinkDemand
The type of the first permission that failed was:
System.Security.PermissionSet
The Zone of the assembly that failed was:
Intranet

Unhandled Exception: System.Security.SecurityException: Request for ConfigurationPermission failed while attempting to access configuration section 'nant'. To allow all callers to access the data for this section, set section attribute 'requirePermission' equal 'false' in the configuration file where this section is declared. ---> System.Security.SecurityException: Request for the permission of type 'System.Configuration.ConfigurationPermission, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' failed.
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, StackCrawlMark& stackMark)
   at System.Security.CodeAccessPermission.Demand()
   at System.Configuration.BaseConfigurationRecord.CheckPermissionAllowed(String configKey, Boolean requirePermission, Boolean isTrustedWithoutAptca)
   --- End of inner exception stack trace ---
   at System.Configuration.BaseConfigurationRecord.CheckPermissionAllowed(String configKey, Boolean requirePermission, Boolean isTrustedWithoutAptca)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at NAnt.Console.ConsoleStub.Framework.GetRuntimeFramework()
   at NAnt.Console.ConsoleStub.Main(String[] args)
```

**Comment by ferventcoder** [comment]
I've definitely seen this and similar - I typically pull folders local, especially if it is a website app as Visual Studio has issues with HGFS (Host Guest Folder Shares) for similar reasons - it's issues are that it doesn't see updates due to file system watcher not seeing updated files.

**Comment by BiggerNoise** [comment]
Thank you for the information. I don't think there's any action for us to take, so I am going to close this.
