### ISSUE TITLE
KeyWordNotSupport: transparentnetworkipresolution / .net 3.5

### ISSUE THREAD

**Issue by ChristianTrolleMikkelsen** [chucknorris/roundhouse#268]
Hi 

With 4.6.1 came "transparentnetworkipresolution" keyword.
Please read: https://blogs.msdn.microsoft.com/dataaccesstechnologies/2016/05/07/connection-timeout-issue-with-net-framework-4-6-1-transparentnetworkipresolution/

Which means that when we run 0.8.6 we get a "Keyword not supported" error since we use this keyword.
How:
We added "TransparentNetworkIPResolution=False;" to the connection string in our kv store where several applications retrieves the connection string from. Applications works fine and have the advantage of the keyword. However this does not apply to rh.

Error when running RH:
Keyword not supported: 'transparentnetworkipresolution'.

RoundhousE encountered an error. You were running in a transaction though, so the database should be in the state it was in prior to this piece running. This does not include a drop/create or any creation of a database, as those items can not run in a transaction.
System.ArgumentException: Keyword not supported: 'transparentnetworkipresolution'.
   at System.Data.Common.DbConnectionOptions.ParseInternal(Hashtable parsetable, String connectionString, Boolean buildChain, Hashtable synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Hashtable synonyms, Boolean useOdbcRules)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(String connectionString, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(String value)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at roundhouse.databases.AdoNetDatabase.GetAdoNetConnection(String conn_string)
   at roundhouse.databases.AdoNetDatabase.open_connection(Boolean with_transaction)
   at roundhouse.migrators.DefaultDatabaseMigrator.open_connection(Boolean with_transaction)
   at roundhouse.runners.RoundhouseMigrationRunner.run()

We have to be able to control this keyword and with 2012 moving forward this keyword AlwaysOn etc can be a big deal.

My guess is that the reason for the error is that RH have a hard binding to 3.5 system.data?

I have 2 suggestions which makes sense from my point of view (there are other options though, they are not pretty) :):

Suggestion 1: Assembly binding redirect, is this possible with rh?

Suggestion 2: Bind to at least 4.6.1 to support the new keyword

**Comment by ChristianTrolleMikkelsen** [comment]
Correct me if im wrong. This seems to have been fixed in the current master?
I just did a master build and the resulting rh.exe does not throw the error when using the keyword.

**Comment by ChristianTrolleMikkelsen** [comment]
I tested with latest master build from build server and it has been fixed :).
We just need a new roundhouse nuget publish :)

**Comment by ChristianTrolleMikkelsen** [comment]
Closing this issue for now
