### ISSUE TITLE
Get differences in unchanged file in RoundhousE 0.9.0

### ISSUE THREAD

**Issue by erikbra** [chucknorris/roundhouse#305]
Have run a script previously with RoundhousE 0.8.6.0. Running all scripts again with 0.9.0. On a particular scipt, I get and error that that script has changed, even though it hasn't. The file is UTF-8 with not BOM. We need to look into this...

```
 myscript.ENV.LOCAL.TEST.sql has changed since the last time it was run. By default this is not allowed - scripts th
  at run once should never change. To change this behavior to a warning, please set warnOnOneTimeScriptChanges to true and run again. Stopping execution.
     at roundhouse.migrators.DefaultDatabaseMigrator.run_sql(String sql_to_run, String script_name, Boolean run_this_script_once, Boolean run_this_script_every_time, In
  t64 version_id, EnvironmentSet environment_set, String repository_version, String repository_path, ConnectionType connection_type)
     at roundhouse.runners.RoundhouseMigrationRunner.traverse_files_and_run_sql(String directory, Int64 version_id, MigrationsFolder migration_folder, EnvironmentSet mi
  grating_environment_set, String repository_version, ConnectionType connection_type)
     at roundhouse.runners.RoundhouseMigrationRunner.log_and_traverse(MigrationsFolder folder, Int64 version_id, String new_version, ConnectionType connection_type)
     at roundhouse.runners.RoundhouseMigrationRunner.run()
  myscript.ENV.LOCAL.TEST.sql has changed since the last time it was run. By default this is not allowed - scripts that run once should
   never change. To change this behavior to a warning, please set warnOnOneTimeScriptChanges to true and run again. Stopping execution.
  System.Exception: myscript.ENV.LOCAL.TEST.sql has changed since the last time it was run. By default this is not allowed - scripts th
  at run once should never change. To change this behavior to a warning, please set warnOnOneTimeScriptChanges to true and run again. Stopping execution.
     at roundhouse.migrators.DefaultDatabaseMigrator.run_sql(String sql_to_run, String script_name, Boolean run_this_script_once, Boolean run_this_script_every_time, In
  t64 version_id, EnvironmentSet environment_set, String repository_version, String repository_path, ConnectionType connection_type)
     at roundhouse.runners.RoundhouseMigrationRunner.traverse_files_and_run_sql(String directory, Int64 version_id, MigrationsFolder migration_folder, EnvironmentSet mi
  grating_environment_set, String repository_version, ConnectionType connection_type)
     at roundhouse.runners.RoundhouseMigrationRunner.log_and_traverse(MigrationsFolder folder, Int64 version_id, String new_version, ConnectionType connection_type)
     at roundhouse.runners.RoundhouseMigrationRunner.run()
     at roundhouse.console.Program.run_migrator(ConfigurationPropertyHolder configuration)
     at roundhouse.console.Program.Main(String[] args)
```

**Comment by BiggerNoise** [comment]
@erikbra - FWIW, the ASCII encoded scripts in my project do not show a change. Hopefully, this is not a widespread issue.

Are you able to share the script and the scripts run table entry?

Since 0.8.6, we have changed two things:
1. The line ending policy: new runs are normalized to unix LE's and old runs are compared with this list:

- As Is
- Normalized to Unix
- Normalized to Windows
- Normalized to Mac

2. We also have some changes to the encoding detection. The default is UTF-8 no BOM, so I would expect that it should have kept working. There's a flag that you can set to change the default encoding, curious if playing with that produces the correct match.

**Comment by erikbra** [comment]
Not able to reproduce at home. I'll re-try at my work laptop tomorrow. It might have been a different `core.autocrlf=true` in my `.gitconfig` at some point. I'll look into it.

**Comment by BiggerNoise** [comment]
@erikbra - Were you able to make this happen on the work laptop? If it was a line ending thing, I would expect it to work unless the original script had a mixture of line endings and now the line endings are uniform.

If they were uniform and they changed uniformly to something else, then I would expect it to work.

**Comment by erikbra** [comment]
Sorry, haven't been able to check it yet, busy days at work. Will try to have a look tomorrow.

**Comment by BiggerNoise** [comment]
Gotcha. I'm going to be fairly out of pocket through the weekend, but I'll be ready to look into anything you find early next week.

**Comment by erikbra** [comment]
Lovely. Hopefully, it's a false alarm. But I'll look into it.

**Comment by erikbra** [comment]
I'm voting to close this one. The file was saved in an invalid encoding (characters were actually iso8859-1, but the file was saved as UTF-8), and doesn't look good when opened in a text editor either. When I converted the file to UTF-8 proper, the hash was the same. User error.
