### ISSUE TITLE
getting error for console.read. using the /silent switch.

### ISSUE THREAD

**Issue by garthbf** [chucknorris/roundhouse#358]

**Comment by garthbf** [comment]
We have RH.exe wrapped with a plugin for urbancode deploy. this has been working for several years.
We upgraded the RH.exe to v0.8.9.0 and now we are getting this error. it is trying to read from the console. 
Any help on why this is doing this would be appreciated. 


==================================================
RoundhousE Structure
==================================================
 Running database type specific tasks.
 Creating RoundhousE schema if it doesn't exist.
 Creating [Version] table if it doesn't exist.
 Creating [ScriptsRun] table if it doesn't exist.
 Creating [ScriptsRunErrors] table if it doesn't exist.
==================================================
Versioning
==================================================
 Attempting to resolve version from D:\uDeploy-Agent-5\var\work\UCD\EDS-uDeploy-DB\_BuildInfo.xml using //buildInfo/version.
Unable to get version from xml file D:\uDeploy-Agent-5\var\work\UCD\EDS-uDeploy-DB\_BuildInfo.xml. File doesn't exist.
 Migrating uDeployProd from version 0.0.0.1 to 0.
 Versioning uDeployProd database with version 0 based on .
==================================================
Migration Scripts
==================================================
--------------------------------------------------
Looking for AlterDatabase scripts in "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\alterDatabase".
--------------------------------------------------
--------------------------------------------------
Looking for Run Before Update scripts in "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\runBeforeUp".
--------------------------------------------------
--------------------------------------------------
Looking for Update scripts in "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\up". These should be one time only scripts.
--------------------------------------------------
--------------------------------------------------
Looking for Run First After Update scripts in "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\runFirstAfterUp".
--------------------------------------------------
--------------------------------------------------
Looking for Function scripts in "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\functions".
--------------------------------------------------
--------------------------------------------------
Looking for View scripts in "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\views".
--------------------------------------------------
--------------------------------------------------
Looking for Stored Procedure scripts in "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\sprocs".
--------------------------------------------------
--------------------------------------------------
Looking for Triggers scripts in "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\triggers".
--------------------------------------------------
--------------------------------------------------
Looking for Index scripts in "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\indexes".
--------------------------------------------------
--------------------------------------------------
Looking for Run after Other Anytime Scripts scripts in "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\runAfterOtherAnyTimeScripts".
--------------------------------------------------
--------------------------------------------------
Looking for Permission scripts in "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\permissions". These scripts will run every time
--------------------------------------------------
 
 
RoundhousE v0.8.9.0 has kicked your database (uDeployProd)! You are now at version 0. All changes and backups can be found at "D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\Logs\migrations\uDeployProd\TST1DM\20181221_131053_8715".
Press any key to continue...
 
Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at roundhouse.console.Program.Main(String[] args)
Finished  - Running RoundhousE at: 12/21/2018 1:10:57 PM

**Comment by garthbf** [comment]
here is the actual command line.
rh.exe /s="xxxxx7\TST1DM" /d="xxxxxProd" /f="D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB" /o="D:\uDeploy-Agent-5\var\work\\UCD\EDS-uDeploy-DB\Logs" --silent /dc /silent

**Comment by erikbra** [comment]
Looks like it might have been compiled with the `DEBUG` flag on, looking at the code. Do you experience the same with the latest 1.0.2 version of RoundhousE?

**Comment by garthbf** [comment]
we are trying the latest version downloaded from NuGet. I will get back to you.

**Comment by erikbra** [comment]
Great to hear that it works in the latest version :)
