### ISSUE TITLE
Aliased Datasource no longer working 

### ISSUE THREAD

**Issue by civica-sfkleach** [chucknorris/roundhouse#360]
Switching from 0.8.6.0 to 1.0.2, I am getting a network error (see below). I have narrowed the cause to being a difficulty with an alias as the 'Data Source' part of the connection string. Version 0.8.6.0 worked with the alias, 1.0.2 needed to be replaced by '(local)' to work.

```
RoundhousE encountered an error. You were running in a transaction though, so the database should be in the state it was in prior to this piece running. This does not include a drop/create or any creation of a database, as those items can not run in a transaction.
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (53): The network path was not found
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
```

**Comment by erikbra** [comment]
This is very interesting, it might be due to differences in the SQL clien libraries used. Do you have an exact example of the form on the connection string you used that worked before, and not with the latest version?

**Comment by civica-sfkleach** [comment]
Yes. The connection string that worked with RH 0.8.6.0 but not RH 1.0.2 is as follows (with trivial renaming to avoid having to get managerial permission to share):

```
Data Source=myaliasname;Initial Catalog=MyCatalog_1234_Suffix;Persist Security Info=True;User ID=MyUser;Password=Password123
```

In order to get this working I needed to change`myaliasname` to `(local)`.

I hope this helps. Apologies for the delay in replying - I did not get a reminder from GitHub, so maybe I am not watching it properly :(
