### ISSUE TITLE
Missing Dependencies on RoundhousE.lib

### ISSUE THREAD

**Issue by BlythMeister** [chucknorris/roundhouse#365]
The nuget listing states:

![image](https://user-images.githubusercontent.com/1046836/52351956-9dbad580-2a23-11e9-889f-6a65137f4345.png)

However many of the other required dependencies for the instances are not lised.

As a result, when using roundhouse.lib without adding any other dependencies manually, you get a runtime error:

```
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at roundhouse.infrastructure.loaders.DefaultInstanceCreator.create_object_from_string_type(String object_to_create)
   at roundhouse.infrastructure.loaders.DefaultInstanceCreator.create_object_from_string_type[T](String object_to_create)
   at roundhouse.infrastructure.app.builders.DatabaseBuilder.build(FileSystemAccess file_system, ConfigurationPropertyHolder configuration_property_holder)
   at roundhouse.infrastructure.app.ApplicationConfiguraton.build_items_for_container(ConfigurationPropertyHolder configuration_property_holder)
   at roundhouse.infrastructure.app.ApplicationConfiguraton.build_the_container(ConfigurationPropertyHolder configuration_property_holder)
   at roundhouse.Migrate.GetMigrationRunner()
   at roundhouse.Migrate.Run()
```

**Comment by erikbra** [comment]
You are definitely right. There has been some ILMerge-ing of the roundhouse.lib. It's starting to cause problems by itself too, I am considering skipping the whole ILMerge thing, and in the process the nuget package dependencies will be solved too.  Thanks for reporting!

**Comment by BlythMeister** [comment]
I've never understood the need to ilmerge these days.
Nuget handles dependencies well when specified correctly ,🙂

**Comment by BlythMeister** [comment]
@erikbra i've raised a PR updating the nuspec to include the missing dependencies :)
