### ISSUE TITLE
RH not running against Oracle DBs on Linux Docker containers

### ISSUE THREAD

**Issue by ninjabadgerpirate** [chucknorris/roundhouse#416]
Hello, I have a Docker image running on a Ubuntu Linux Container where I have installed DotNetCore 2.1, Roundhouse and the [Oracle client tools for Linux x64 systems](https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html) (as mentioned in the [wiki here](https://github.com/chucknorris/roundhouse/wiki/Oracle)) however whenever I run the rh command I get the following error:

> System.NullReferenceException: A type could not be created from the object you passed. "roundhouse.databases.oracle.OracleDatabase, roundhouse.databases.oracle" resolves to null.

Could you tell me if there's a specific version of the Oracle Client tools that is expected?  Or if there is some missing configuration or Environment variable that I need to provide?  Unfortunately the wiki is not very clear on this point.

**Comment by erikbra** [comment]
Hi, ninjabadgerpirate , sorry for the issues when running against Oracle. That said, we do have a lot of issues on Oracle, and we are running with very old Oracle drivers. We have an issue from 2015 on converting to the managed Oracle provider, but no one has fixed it since then (#171 )

The docker image is based on Linux and .net core, and the oracle provider does not, unfortunately, in its current form, work on anything else than Windows.

I have very little experience with Oracle the latest 15 years, so testing of this migration would be a bit lacking. So, to be frank, we are dependent on someone with Oracle competence stepping up and pulling the Oracle implementation forward technology-wise.

This is the mixed blessing of Open source, I'm afraid. Nothing gets done if nobody does it. And, I, as maintainer, don't have the time and resources to solve everything. Collaborative effort is a prerequisite.

**Comment by Zun1k** [comment]
Hi, I tried to test it over oracle v21 packages, but still same problem.

`A type could not be created from the object you passed. "roundhouse.databases.oracle.OracleDatabase, roundhouse.databases.oracle" resolves to null.
System.NullReferenceException: A type could not be created from the object you passed. "roundhouse.databases.oracle.OracleDatabase, roundhouse.databases.oracle" resolves to null.
   at roundhouse.infrastructure.loaders.DefaultInstanceCreator.create_object_from_string_type(String object_to_create) in C:\projects\roundhouse\product\roundhouse.core\infrastructure\loaders\DefaultInstanceCreator.cs:line 29
   at roundhouse.infrastructure.loaders.DefaultInstanceCreator.create_object_from_string_type[T](String object_to_create) in C:\projects\roundhouse\product\roundhouse.core\infrastructure\loaders\DefaultInstanceCreator.cs:line 19
   at roundhouse.infrastructure.app.builders.DatabaseBuilder.build(FileSystemAccess file_system, ConfigurationPropertyHolder configuration_property_holder) in C:\projects\roundhouse\product\roundhouse.core\infrastructure.app\builders\DatabaseBuilder.cs:line 32
   at roundhouse.infrastructure.app.ApplicationConfiguraton.build_items_for_container(ConfigurationPropertyHolder configuration_property_holder) in C:\projects\roundhouse\product\roundhouse.core\infrastructure.app\ApplicationConfiguraton.cs:line 174
   at roundhouse.infrastructure.app.ApplicationConfiguraton.build_the_container(ConfigurationPropertyHolder configuration_property_holder) in C:\projects\roundhouse\product\roundhouse.core\infrastructure.app\ApplicationConfiguraton.cs:line 159
   at roundhouse.console.Program.set_up_configuration_and_build_the_container(String[] args, Mode mode) in C:\projects\roundhouse\product\roundhouse.console\Program.cs:line 103
   at roundhouse.console.Program.Main(String[] args) in C:\projects\roundhouse\product\roundhouse.console\Program.cs:line 64
`

problematic line :)

`database_to_migrate = DefaultInstanceCreator.create_object_from_string_type<Database>(database_type + ", " + merge_assembly_name);
`

Did anybody solve this somehow?
Thx

**Comment by erikbra** [comment]
Hi, @ninjabadgerpirate - could you please check out if my reboot of RoundhousE, called grate, solved this issue? It uses much newer Oracle libraries.

It should be a more-or-less drop-in replacement to RoundhousE: https://erikbra.github.io/grate/

**Comment by ninjabadgerpirate** [comment]
Glad to hear about Grate. I will definitely give it a try and let you know what I find.

**Comment by erikbra** [comment]
Please do, and do get back to me on any Oracle issues, if you still use Oracle, as the Oracle implementation is not tested very thoroughly, as I don't use Oracle on a day-to-day basis.
