### ISSUE TITLE
Postgres Docker Image provider issue with rh

### ISSUE THREAD

**Issue by ManojLingala** [chucknorris/roundhouse#418]
I have multiple postgres docker images running for different purposes , image pointing out to default port is working fine 

        {
            var csb = new NpgsqlConnectionStringBuilder();
            
            csb.Host = host;
            csb.Database = database;
            csb.Username = username;
            csb.Password = password;
            csb.Port = 5432;

            return csb.ToString();
        }
However , when I override the port as below                                                        
``rh --dt="pg" --files=App_data\db --cs="Host=localhost;User Id=postgres;Password=xxxxxx;Database=image2;Port=5435"``         

 I'm getting timeout issue roundhouse.databases.postgresql.PostgreSQLDatabase` with provider Npgsql does not provide a facility for creating a database at this time.
System.TimeoutException: The operation has timed out.
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()

The same docker image is pretty accessible and working via docker compose for my integration testing . Not sure why it is timing out with rh .

**Comment by ManojLingala** [comment]
Fixed it by providing image gateway I.p as a host instead of localhost ...

**Comment by erikbra** [comment]
Does this mean your issue is solved, @ManojLingala ?
