### ISSUE TITLE
MySQL delimiter issues

### ISSUE THREAD

**Issue by Rory-Sullivan** [chucknorris/roundhouse#443]
Hi there,
I ran into an issue running a MySQL script today. The script runs fine when run from MySQL Workbench but fails when run by Roundhouse. The script creates a new function and the issue seems to be caused by a block comment that comes after the final DELIMITER statement.
This issue seems to be related to #377. Removing the comment resolved the issue.
Let me know if I can provide any more information, many thanks!

Roundhouse Error:
RoundhousE encountered an error.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at roundhouse.databases.mysql.MySqlDatabase.run_sql(String sql_to_run, ConnectionType connection_type) in C:\projects\roundhouse\product\roundhouse.databases.mysql\MySqlDatabase.cs:line 193
   at roundhouse.migrators.DefaultDatabaseMigrator.run_sql(String sql_to_run, String script_name, Boolean run_this_script_once, Boolean run_this_script_every_time, Int64 version_id, EnvironmentSet environment_set, String repository_version, String repository_path, ConnectionType connection_type) in C:\projects\roundhouse\product\roundhouse.core\migrators\DefaultDatabaseMigrator.cs:line 206
   at roundhouse.runners.RoundhouseMigrationRunner.traverse_files_and_run_sql(String directory, Int64 version_id, MigrationsFolder migration_folder, EnvironmentSet migrating_environment_set, String repository_version, ConnectionType connection_type) in C:\projects\roundhouse\product\roundhouse.core\runners\RoundhouseMigrationRunner.cs:line 290
   at roundhouse.runners.RoundhouseMigrationRunner.log_and_traverse(MigrationsFolder folder, Int64 version_id, String new_version, ConnectionType connection_type) in C:\projects\roundhouse\product\roundhouse.core\runners\RoundhouseMigrationRunner.cs:line 222
   at roundhouse.runners.RoundhouseMigrationRunner.run() in C:\projects\roundhouse\product\roundhouse.core\runners\RoundhouseMigrationRunner.cs:line 154
Index was outside the bounds of the array.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at roundhouse.databases.mysql.MySqlDatabase.run_sql(String sql_to_run, ConnectionType connection_type) in C:\projects\roundhouse\product\roundhouse.databases.mysql\MySqlDatabase.cs:line 193
   at roundhouse.migrators.DefaultDatabaseMigrator.run_sql(String sql_to_run, String script_name, Boolean run_this_script_once, Boolean run_this_script_every_time, Int64 version_id, EnvironmentSet environment_set, String repository_version, String repository_path, ConnectionType connection_type) in C:\projects\roundhouse\product\roundhouse.core\migrators\DefaultDatabaseMigrator.cs:line 206
   at roundhouse.runners.RoundhouseMigrationRunner.traverse_files_and_run_sql(String directory, Int64 version_id, MigrationsFolder migration_folder, EnvironmentSet migrating_environment_set, String repository_version, ConnectionType connection_type) in C:\projects\roundhouse\product\roundhouse.core\runners\RoundhouseMigrationRunner.cs:line 290
   at roundhouse.runners.RoundhouseMigrationRunner.log_and_traverse(MigrationsFolder folder, Int64 version_id, String new_version, ConnectionType connection_type) in C:\projects\roundhouse\product\roundhouse.core\runners\RoundhouseMigrationRunner.cs:line 222
   at roundhouse.runners.RoundhouseMigrationRunner.run() in C:\projects\roundhouse\product\roundhouse.core\runners\RoundhouseMigrationRunner.cs:line 154
   at roundhouse.console.Program.run_migrator(ConfigurationPropertyHolder configuration) in C:\projects\roundhouse\product\roundhouse.console\Program.cs:line 589
   at roundhouse.console.Program.Main(String[] args) in C:\projects\roundhouse\product\roundhouse.console\Program.cs:line 66

**Comment by erikbra** [comment]
Hi, @Rory-Sullivan , I've abandoned RoundhousE in favour of a brand-new implementation, called grate, could you please check if that works in you scenario? It should be almost a drop-in replacement:

https://erikbra.github.io/grate/

**Comment by erikbra** [comment]
Any luck trying out grate, @Rory-Sullivan ?

**Comment by Rory-Sullivan** [comment]
Hi @erikbra, I had a look at upgrading our project from RoundhousE to grate. There is still some work to do before we are fully up and running on it but I can confirm that it does appear to resolve this issue. I have some comments about the upgrade process that I will make over on the grate repository.
