### ISSUE TITLE
.NET 5/6 file copy error

### ISSUE THREAD

**Issue by rpopovych** [chucknorris/roundhouse#446]
When using RH library in .NET 5/6, the following error happens:

```
Unable to copy ./Scripts/db1/OneTime/YYYY-MM-DD-Initials-JiraTicket-1-SampleRoleCreation.sql to ./Scripts/db1/OneTime. 
System.DllNotFoundException: Unable to load shared library 'kernel32' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32: cannot open shared object file: No such file or directory
   at roundhouse.infrastructure.filesystem.DotNetFileSystemAccess.CopyFileA(String lpExistingFileName, String lpNewFileName, Int32 bFailIfExists)
   at roundhouse.infrastructure.filesystem.DotNetFileSystemAccess.file_copy_unsafe(String source_file_name, String destination_file_name, Boolean overwrite_the_existing_file)
   at roundhouse.runners.RoundhouseMigrationRunner.copy_to_change_drop_folder(String sql_file_ran, Folder migration_folder)
   at roundhouse.runners.RoundhouseMigrationRunner.traverse_files_and_run_sql(String directory, Int64 version_id, MigrationsFolder migration_folder, EnvironmentSet migrating_environment_set, String repository_version, ConnectionType connection_type)
```

The issue is here: https://github.com/chucknorris/roundhouse/blob/0f17f6967a1b3a5bb1d1b63f3574a7e8ba3e1294/product/roundhouse.core/infrastructure/filesystem/DotNetFileSystemAccess.cs#L20

There is handing for Mono & .NET Core, but with .NET 5 the `Core` naming has been dropped.

I see this deliberation [here](https://github.com/chucknorris/roundhouse/issues/438), but has anyone tried to at least support use of libraries in .NET 6? I don't believe that would require upgrading the project to .NET 6 and it might be just this one place to fix.

.NET 3.1 End of Support is at the end of 2022: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by kbialkowski** [comment]
@rpopovych 
Hi got same error
When trying to run under the docker container with .NET 5 I get 
![image](https://user-images.githubusercontent.com/3984259/202711040-a609e1be-7057-4e6c-925d-0ba46f3e1a8d.png)

Did you manage to find solution?
