### ISSUE TITLE
Unable to create database

### ISSUE THREAD

**Issue by Rory-Sullivan** [chucknorris/roundhouse#449]
I am having issues running Roundhouse against a new install of MySQL server (8.0.29). Roundhouse fails to create a new database on the server, full error message below.

This SO post suggests upgrading the MySQL connector dependency, https://stackoverflow.com/questions/68645324/system-notsupportedexception-character-set-utf8mb3-is-not-supported-by-net-f

Error message:
roundhouse.databases.mysql.MySqlDatabase with provider MySql.Data.MySqlClient does not provide a facility for creating a database at this time.
System.NotSupportedException: Character set 'utf8mb3' is not supported by .Net Framework.
   at MySql.Data.MySqlClient.CharSetMap.GetCharacterSet(DBVersion version, String charSetName)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.MySqlField.set_CharacterSetIndex(Int32 value)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlCommand.ResetReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.Driver.ReportWarnings(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.CloseQuery(MySqlConnection connection, Int32 statementId)
   at MySql.Data.MySqlClient.MySqlCommand.Close(MySqlDataReader reader)
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose(Boolean disposing)
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteScalar()
   at roundhouse.databases.AdoNetDatabase.<>c__DisplayClass15_0.<run_sql_scalar>b__0() in C:\projects\roundhouse\product\roundhouse.core\databases\AdoNetDatabase.cs:line 160
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at roundhouse.databases.AdoNetDatabase.run_sql_scalar(String sql_to_run, ConnectionType connection_type, IList`1 parameters) in C:\projects\roundhouse\product\roundhouse.core\databases\AdoNetDatabase.cs:line 160
   at roundhouse.databases.DefaultDatabase`1.run_sql_scalar(String sql_to_run, ConnectionType connection_type) in C:\projects\roundhouse\product\roundhouse.core\databases\DefaultDatabase.cs:line 219
   at roundhouse.databases.DefaultDatabase`1.run_sql_scalar_boolean(String sql_to_run, ConnectionType connection_type) in C:\projects\roundhouse\product\roundhouse.core\databases\DefaultDatabase.cs:line 138
   at roundhouse.databases.DefaultDatabase`1.create_database_if_it_doesnt_exist(String custom_create_database_script) in C:\projects\roundhouse\product\roundhouse.core\databases\DefaultDatabase.cs:line 122

**Comment by erikbra** [comment]
Hi, @Rory-Sullivan , maybe this is not relevant to you, but as a tip, due to the many ancient-ish dependencies in RoundhousE, I gave up maintaining it about a year back, and made a re-implementation from scratch, called grate. More info on the decision/process can be found here: https://github.com/chucknorris/roundhouse/issues/438#issuecomment-927371525

Please feel free to check out grate, as it is been more actively developed, and is beginning to get a bit of traction from other contributors as well.

**Comment by Rory-Sullivan** [comment]
Hi @erikbra, I am aware of grate and we have previously tried to move from Roundhouse to grate but I remember running into some issues at that time. However I will explore this option again as it has been a while since so this may have changed. I will let you know how this goes.

Thanks!
